version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Nodejs-aws-sam-sqs-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1n49ran6uirlg"
s3_prefix = "Nodejs-aws-sam-sqs-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
